[0m[[0minfo[0m] [0mRunning common.utils.ZookeeperOps common.utils.ZookeeperOps localhost:2181 list /[0m
[0m[[0mdebug[0m] [0mStarting sandboxed run...[0m
[0m[[0mdebug[0m] [0mWaiting for threads to exit or System.exit to be called.[0m
[0m[[0mdebug[0m] [0mWaiting for thread run-main to exit[0m
[0m[[0mdebug[0m] [0m  Classpath:[0m
[0m[[0mdebug[0m] [0m	/Users/v765849/git/commonutils/target/scala-2.10/classes[0m
[0m[[0mdebug[0m] [0m	/Users/v765849/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.10.4.jar[0m
[0m[[0mdebug[0m] [0m	/Users/v765849/.ivy2/cache/org.apache.curator/curator-framework/bundles/curator-framework-2.7.1.jar[0m
[0m[[0mdebug[0m] [0m	/Users/v765849/.ivy2/cache/org.apache.curator/curator-client/bundles/curator-client-2.7.1.jar[0m
[0m[[0mdebug[0m] [0m	/Users/v765849/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.6.jar[0m
[0m[[0mdebug[0m] [0m	/Users/v765849/.ivy2/cache/org.apache.zookeeper/zookeeper/jars/zookeeper-3.4.6.jar[0m
[0m[[0mdebug[0m] [0m	/Users/v765849/.ivy2/cache/org.slf4j/slf4j-log4j12/jars/slf4j-log4j12-1.7.6.jar[0m
[0m[[0mdebug[0m] [0m	/Users/v765849/.ivy2/cache/log4j/log4j/bundles/log4j-1.2.17.jar[0m
[0m[[0mdebug[0m] [0m	/Users/v765849/.ivy2/cache/jline/jline/jars/jline-0.9.94.jar[0m
[0m[[0mdebug[0m] [0m	/Users/v765849/.ivy2/cache/junit/junit/jars/junit-3.8.1.jar[0m
[0m[[0mdebug[0m] [0m	/Users/v765849/.ivy2/cache/io.netty/netty/bundles/netty-3.7.0.Final.jar[0m
[0m[[0mdebug[0m] [0m	/Users/v765849/.ivy2/cache/com.google.guava/guava/bundles/guava-16.0.1.jar[0m
[0m[[0mdebug[0m] [0m	/Users/v765849/.ivy2/cache/scala_2.10/sbt_0.13/com.github.mpeltonen/sbt-idea/jars/sbt-idea-1.6.0.jar[0m
[0m[[0mdebug[0m] [0m	/Users/v765849/.ivy2/cache/commons-io/commons-io/jars/commons-io-2.0.1.jar[0m
[0m[[31merror[0m] [0m(run-main) scala.MatchError: localhost:2181 (of class java.lang.String)[0m
scala.MatchError: localhost:2181 (of class java.lang.String)
	at common.utils.ZookeeperOps$.main(ZookeeperOps.scala:17)
	at common.utils.ZookeeperOps.main(ZookeeperOps.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sbt.Run.invokeMain(Run.scala:72)
	at sbt.Run.run0(Run.scala:65)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
	at sbt.TrapExit$.sbt$TrapExit$$executeMain$1(TrapExit.scala:33)
	at sbt.TrapExit$$anon$1.run(TrapExit.scala:42)
[0m[[0mdebug[0m] [0m	Thread run-main exited.[0m
[0m[[0mdebug[0m] [0mInterrupting remaining threads (should be all daemons).[0m
[0m[[0mdebug[0m] [0mSandboxed run complete..[0m
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
	at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:1628)
	at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:1628)
	at scala.Option.foreach(Option.scala:236)
	at sbt.BuildCommon$class.toError(Defaults.scala:1628)
	at sbt.Defaults$.toError(Defaults.scala:34)
	at sbt.Defaults$$anonfun$runTask$1$$anonfun$apply$36$$anonfun$apply$37.apply(Defaults.scala:647)
	at sbt.Defaults$$anonfun$runTask$1$$anonfun$apply$36$$anonfun$apply$37.apply(Defaults.scala:645)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[0m[[31merror[0m] [0m(compile:[31mrun[0m) Nonzero exit code: 1[0m
